name: t2liver
channels:
  - defaults
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - bzip2=1.0.8
  - ca-certificates=2025.12.2
  - expat=2.7.3
  - ld_impl_linux-64=2.44
  - libexpat=2.7.3
  - libffi=3.4.4
  - libgcc=15.2.0
  - libgcc-ng=15.2.0
  - libgomp=15.2.0
  - libnsl=2.0.0
  - libstdcxx=15.2.0
  - libstdcxx-ng=15.2.0
  - libuuid=1.41.5
  - libxcb=1.17.0
  - libzlib=1.3.1
  - ncurses=6.5
  - openssl=3.0.18
  - pip=25.3
  - pthread-stubs=0.3
  - pydicom=3.0.1
  - python=3.10.19
  - readline=8.3
  - setuptools=80.9.0
  - sqlite=3.51.0
  - tk=8.6.15
  - wheel=0.45.1
  - xorg-libx11=1.8.12
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - xorg-xorgproto=2024.1
  - xz=5.6.4
  - zlib=1.3.1
  - pip:
      - absl-py==2.3.1
      - acvl-utils==0.2.5
      - anyio==4.12.0
      - argparse==1.4.0
      - batchgenerators==0.25.1
      - batchgeneratorsv2==0.3.0
      - blinker==1.9.0
      - blosc2==3.12.2
      - certifi==2026.1.4
      - charset-normalizer==3.4.4
      - click==8.3.1
      - connected-components-3d==3.26.1
      - contourpy==1.3.2
      - cycler==0.12.1
      - dicom2nifti==2.6.2
      - dynamic-network-architectures==0.4.2
      - einops==0.8.1
      - exceptiongroup==1.3.1
      - fft-conv-pytorch==1.2.0
      - filelock==3.20.2
      - flask==3.1.2
      - flask-cors==6.0.1
      - fonttools==4.61.0
      - fsspec==2025.12.0
      - future==1.0.0
      - graphviz==0.21
      - grpcio==1.76.0
      - h11==0.16.0
      - hf-xet==1.2.0
      - httpcore==1.0.9
      - httpx==0.28.1
      - huggingface-hub==1.2.3
      - idna==3.11
      - imagecodecs==2025.3.30
      - imageio==2.37.2
      - importlib-resources==6.5.2
      - itsdangerous==2.2.0
      - jinja2==3.1.6
      - joblib==1.5.3
      - kiwisolver==1.4.9
      - lazy-loader==0.4
      - linecache2==1.0.0
      - markdown==3.10
      - markupsafe==3.0.3
      - matplotlib==3.10.7
      - mpmath==1.3.0
      - msgpack==1.1.2
      - ndindex==1.10.1
      - networkx==3.4.2
      - nibabel==5.3.3
      - nnunetv2==2.6.2
      - numexpr==2.14.1
      - numpy==2.2.6
      - nvidia-cublas-cu12==12.8.4.1
      - nvidia-cuda-cupti-cu12==12.8.90
      - nvidia-cuda-nvrtc-cu12==12.8.93
      - nvidia-cuda-runtime-cu12==12.8.90
      - nvidia-cudnn-cu12==9.10.2.21
      - nvidia-cufft-cu12==11.3.3.83
      - nvidia-cufile-cu12==1.13.1.3
      - nvidia-curand-cu12==10.3.9.90
      - nvidia-cusolver-cu12==11.7.3.90
      - nvidia-cusparse-cu12==12.5.8.93
      - nvidia-cusparselt-cu12==0.7.1
      - nvidia-nccl-cu12==2.27.5
      - nvidia-nvjitlink-cu12==12.8.93
      - nvidia-nvshmem-cu12==3.3.20
      - nvidia-nvtx-cu12==12.8.90
      - packaging==25.0
      - pandas==2.3.3
      - pillow==12.0.0
      - platformdirs==4.5.1
      - protobuf==6.33.2
      - py-cpuinfo==9.0.0
      - pyarrow==23.0.0
      - pyparsing==3.2.5
      - python-dateutil==2.9.0.post0
      - python-gdcm==3.2.2
      - pytz==2025.2
      - pyyaml==6.0.3
      - requests==2.32.5
      - safetensors==0.7.0
      - scikit-image==0.25.2
      - scikit-learn==1.7.2
      - scipy==1.15.3
      - seaborn==0.13.2
      - shellingham==1.5.4
      - simpleitk==2.5.3
      - six==1.17.0
      - sympy==1.14.0
      - tensorboard==2.20.0
      - tensorboard-data-server==0.7.2
      - threadpoolctl==3.6.0
      - tifffile==2025.5.10
      - timm==1.0.22
      - torch==2.9.1
      - torchvision==0.24.1
      - totalsegmentator==2.12.0
      - tqdm==4.67.1
      - traceback2==1.4.0
      - triton==3.5.1
      - typer-slim==0.21.0
      - typing-extensions==4.15.0
      - tzdata==2025.3
      - unittest2==1.1.0
      - urllib3==2.6.2
      - werkzeug==3.1.4
      - xvfbwrapper==0.2.18
      - yacs==0.1.8
prefix: /home/homesOnMaster/dgeiger/miniforge3/envs/t2liver
